### ISSUE TITLE
problem with tup compiling [compile without tup]

### ISSUE THREAD

**Issue by Fixallmyproblems** [ametisf/dwc#1]
I have all of the following dependencies and I am attempting to build the project with tup
tup init works fine (I did it in the root of the package folder)
I have tcc installed correctly but when I do either tup or tup upd I get this error http://i.imgur.com/3TdxK5E.jpg
If you could provide me with some info on how to fix this, or a Makefile, or a fix within the actual package would be nice, I'm building on a Void Linux musl libc host (I'm using this one because I like using unknown projects and it's suckless and wayland, seems like the only one that would suit me)

**Comment by ametisf** [comment]
Does Void provide a package for tup or have you built it from source? It seems like problem with tup.
I will provide a build.sh script which tup can generate so you will not need tup to compile project.

**Comment by Fixallmyproblems** [comment]
Thank you, I don't get back home in another 5 hours so i'll get back to you and tell you if the build is successful, I'm using the package of tup because it gives me weird musl libc errors when I tried to compile tup from source so I just got the latest version from void's servers

**Comment by Fixallmyproblems** [comment]
hey don't want to bother you too much but can you provide build.sh scripts for dmenu, dstatus and st as well? The GUI works fine it's just it's not usable without these things.

**Comment by ametisf** [comment]
I've added `build.sh` scripts to dstatus, dmenu, stest and st. Let me know if something doesn't work for you.
